# Generated by Django 2.1.2 on 2018-12-16 17:45

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include(('apps.core.urls', "core", ), namespace='core')),
    path('', include(('apps.store.urls', "store", ), namespace='store')),
]
